DROP TABLE IF EXISTS covid_data;

CREATE TABLE IF NOT EXISTS covid_data (
    date_of_interest DATE,
    case_count INT,
    probable_case_count INT,
    hospitalized_count INT,
    death_count INT,
    death_count_probable INT,
    case_count_7day_avg INT,
    all_case_count_7day_avg INT,
    hosp_count_7day_avg INT,
    death_count_7day_avg INT,
    all_death_count_7day_avg INT,
    bx_case_count INT,
    bx_probable_case_count INT,
    bx_hospitalized_count INT,
    bx_death_count INT,
    bx_probable_death_count INT,
    bx_case_count_7day_avg INT,
    bx_all_case_count_7day_avg INT,
    bx_hospitalized_count_7day_avg INT,
    bx_death_count_7day_avg INT,
    bx_all_death_count_7day_avg INT,
    bk_case_count INT,
    bk_probable_case_count INT,
    bk_hospitalized_count INT,
    bk_death_count INT,
    bk_probable_death_count INT,
    bk_case_count_7day_avg INT,
    bk_all_case_count_7day_avg INT,
    bk_hospitalized_count_7day_avg INT,
    bk_death_count_7day_avg INT,
    bk_all_death_count_7day_avg INT,
    mn_case_count INT,
    mn_probable_case_count INT,
    mn_hospitalized_count INT,
    mn_death_count INT,
    mn_probable_death_count INT,
    mn_case_count_7day_avg INT,
    mn_all_case_count_7day_avg INT,
    mn_hospitalized_count_7day_avg INT,
    mn_death_count_7day_avg INT,
    mn_all_death_count_7day_avg INT,
    qn_case_count INT,
    qn_probable_case_count INT,
    qn_hospitalized_count INT,
    qn_death_count INT,
    qn_probable_death_count INT,
    qn_case_count_7day_avg INT,
    qn_all_case_count_7day_avg INT,
    qn_hospitalized_count_7day_avg INT,
    qn_death_count_7day_avg INT,
    qn_all_death_count_7day_avg INT,
    si_case_count INT,
    si_probable_case_count INT,
    si_hospitalized_count INT,
    si_death_count INT,
    si_probable_death_count INT,
    si_case_count_7day_avg INT,
    si_all_case_count_7day_avg INT,
    si_hospitalized_count_7day_avg INT,
    si_death_count_7day_avg INT,
    si_all_death_count_7day_avg INT,
    incomplete INT
);


-- TRUNCATE covid_data;